service: boomerang-catcher
provider:
  name: aws
  runtime: nodejs8.10
  region: eu-west-2
functions:
  beacon:
    handler: handlers.beacon
    environment:
      webhook: ${env:BOOMERANGCATCHER_WEBHOOK_URL}
    events:
      - http:
          method: get
          path: beacon
          cors: true
      - http:
          method: post
          path: beacon
          cors: true
