version: 2
jobs:
  build:
    working_directory: /tmp/build
    docker:
      - image: tegud/circleci-nodejs-serverless
    steps:
      - checkout
      - run:
          name: install dependencies
          command: npm install
      - run:
          name: test
          command: npm test
      - run:
          name: deploy
          command: serverless deploy
